name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: nvcr.io/nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t dm_control:1.2 ./docker
    - name: Build the Docker container
      run: docker run --gpus 1 -i --rm --name mario_ai -p 9280:2980 -v $(pwd):/home/cpx0/workspace -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix:10.0 dm_control:1.2
